language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo

addons:
  apt:
    packages:
      - libusb-1.0-0-dev